<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_ACCESS_LEVELS_0'] = 'install';
$GLOBALS['CONFIG_ACCESS_LEVELS_1'] = 'install';
$GLOBALS['CONFIG_ACCESS_LEVELS_2'] = 'install';
$GLOBALS['CONFIG_ACCESS_LEVELS_3'] = 'install';
$GLOBALS['CONFIG_ACCESS_LEVELS_4'] = 'install';
$GLOBALS['CONFIG_ACCESS_LEVELS_5'] = 'install';
