<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_MYSQL_PCONNECT'] = '0';
$GLOBALS['CONFIG_MYSQL_HOST_GS'] = 'localhost';
$GLOBALS['CONFIG_MYSQL_HOST_LS'] = 'localhost';
$GLOBALS['CONFIG_MYSQL_USER_GS'] = 'root';
$GLOBALS['CONFIG_MYSQL_USER_LS'] = 'root';
$GLOBALS['CONFIG_MYSQL_PASS_GS'] = '';
$GLOBALS['CONFIG_MYSQL_PASS_LS'] = '';
$GLOBALS['CONFIG_MYSQL_NAME_GS'] = 'dragon_eye';
$GLOBALS['CONFIG_MYSQL_NAME_LS'] = 'dragon_eye';
$GLOBALS['CONFIG_MSSQL_PCONNECT'] = '1';
$GLOBALS['CONFIG_MSSQL_HOST_GS'] = '(local)';
$GLOBALS['CONFIG_MSSQL_HOST_LS'] = '(local)';
$GLOBALS['CONFIG_MSSQL_USER_GS'] = 'sa';
$GLOBALS['CONFIG_MSSQL_USER_LS'] = 'sa';
$GLOBALS['CONFIG_MSSQL_PASS_GS'] = '';
$GLOBALS['CONFIG_MSSQL_PASS_LS'] = '';
$GLOBALS['CONFIG_MSSQL_NAME_GS'] = 'lin2world';
$GLOBALS['CONFIG_MSSQL_NAME_LS'] = 'lin2db';
$GLOBALS['CONFIG_MYSQL_FORUM_HOST'] = 'notyet';
$GLOBALS['CONFIG_MYSQL_FORUM_USER'] = 'notyet';
$GLOBALS['CONFIG_MYSQL_FORUM_PASS'] = 'notyet';
$GLOBALS['CONFIG_MYSQL_FORUM_NAME'] = 'notyet';
