<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_WEBSITE_NAME'] = 'DragonEye';
$GLOBALS['CONFIG_WEBSITE_URL'] = 'http://127.0.0.1';
$GLOBALS['CONFIG_DATE_TIMEZONE'] = 'Europe/London';
$GLOBALS['CONFIG_DATE_FORMAT'] = 'd/M/Y h:i:s';
$GLOBALS['CONFIG_CMS_INSTALLED'] = '0';
$GLOBALS['CONFIG_SERVER_TYPE'] = '0';
$GLOBALS['CONFIG_USE_SQLSRV'] = '1';
$GLOBALS['CONFIG_DEFAULT_PAGE'] = 'home';
$GLOBALS['CONFIG_EXEC_TIME'] = '1';
$GLOBALS['CONFIG_QUERY_COUNT'] = '1';
$GLOBALS['CONFIG_CHECK_LOGGED'] = '5';
$GLOBALS['CONFIG_ATTACK_MODE'] = '0';
$GLOBALS['CONFIG_ATTACK_MESSAGE'] = '<div id="maintenance">Website in quarantine. All database related functions are currently disabled. Stay tuned!</div>';
$GLOBALS['CONFIG_DEV_DEBUG'] = '1';
$GLOBALS['CONFIG_ENABLE_ONLINE'] = '0';
$GLOBALS['CONFIG_ONLINE_CACHE'] = '60';
$GLOBALS['CONFIG_ENABLE_STATUS'] = '0';
$GLOBALS['CONFIG_STATUS_LOGIN_IP'] = '127.0.0.1';
$GLOBALS['CONFIG_STATUS_LOGIN_PORT'] = '80';
$GLOBALS['CONFIG_STATUS_SERVER_IP'] = '127.0.0.1';
$GLOBALS['CONFIG_STATUS_SERVER_PORT'] = '80';
$GLOBALS['CONFIG_STATUS_TIMEOUT'] = '5';
$GLOBALS['CONFIG_STATUS_CACHE'] = '15';
$GLOBALS['CONFIG_ADMIN_MAIL'] = 'yourmail@yoursite.com';
$GLOBALS['CONFIG_MAIL_TYPE'] = '0';
$GLOBALS['CONFIG_SMTP_SERVER'] = 'smtp.yoursmtp';
$GLOBALS['CONFIG_SMTP_PORT'] = '25';
$GLOBALS['CONFIG_SMTP_USER'] = 'yourmail@yoursite.com';
$GLOBALS['CONFIG_SMTP_PASS'] = '';
$GLOBALS['CONFIG_SMTP_TIMEOUT'] = '10';
$GLOBALS['CONFIG_REGISTER_ACTIVATION'] = '0';
$GLOBALS['CONFIG_REGISTER_ACTIVATION_SESS_EXPIRE'] = '900';
$GLOBALS['CONFIG_REFER_SYSTEM'] = '0';
$GLOBALS['CONFIG_CHANGE_PASS'] = '0';
$GLOBALS['CONFIG_RECOVER_PASS'] = '0';
$GLOBALS['CONFIG_RECOVER_SESS_EXPIRE'] = '900';
$GLOBALS['CONFIG_SERVER_CHRONICLE'] = 'Interlude';
$GLOBALS['CONFIG_SERVER_XP'] = '1';
$GLOBALS['CONFIG_SERVER_SP'] = '10';
$GLOBALS['CONFIG_SERVER_DROP'] = '100';
$GLOBALS['CONFIG_SERVER_ADENA'] = '1000';
