<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_HOME_ACCESS'] = '1';
$GLOBALS['CONFIG_HOME_RES_PER_PAGE'] = '5';
$GLOBALS['CONFIG_HOME_TOTAL_RESULTS'] = '20';
$GLOBALS['CONFIG_HOME_TOTAL_ARCHIVED'] = '30';
$GLOBALS['CONFIG_DOWNLOADS_ACCESS'] = '1';
$GLOBALS['CONFIG_DOWNLOADS_RES_PER_PAGE'] = '25';
$GLOBALS['CONFIG_DOWNLOADS_TOTAL_RESULTS'] = '20';
$GLOBALS['CONFIG_DOWNLOADS_TOTAL_ARCHIVED'] = '30';
$GLOBALS['CONFIG_FEATURES_ACCESS'] = '1';
$GLOBALS['CONFIG_FEATURES_RES_PER_PAGE'] = '50';
$GLOBALS['CONFIG_FEATURES_TOTAL_RESULTS'] = '20';
$GLOBALS['CONFIG_FEATURES_TOTAL_ARCHIVED'] = '30';
$GLOBALS['CONFIG_STAFF_ACCESS'] = '1';
$GLOBALS['CONFIG_STAFF_RES_PER_PAGE'] = '25';
$GLOBALS['CONFIG_STAFF_TOTAL_RESULTS'] = '20';
$GLOBALS['CONFIG_STAFF_TOTAL_ARCHIVED'] = '30';
$GLOBALS['CONFIG_COMMUNITY_ACCESS'] = '1';
$GLOBALS['CONFIG_ACCOUNT_ACCESS'] = '1';
$GLOBALS['CONFIG_STATISTICS_ACCESS'] = '1';
$GLOBALS['CONFIG_ADMINISTRATION_ACCESS'] = '5';
$GLOBALS['CONFIG_ACTIVATE_ACCESS'] = '1';
$GLOBALS['CONFIG_RECOVER_ACCESS'] = '1';
$GLOBALS['CONFIG_SIGNATURE_ACCESS'] = '1';
