<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_STATS_INVENTORY_ENABLED'] = '1';
$GLOBALS['CONFIG_STATS_INVENTORY_GUESTS'] = '1';
$GLOBALS['CONFIG_STATS_INVENTORY_VIEWABLE'] = '3';
$GLOBALS['CONFIG_STATS_INVENTORY_WAREHOUSE'] = '1';
$GLOBALS['CONFIG_STATS_INVENTORY_IMAGES'] = 'http://dragoneyecms.com/items/';
$GLOBALS['CONFIG_STATS_INVENTORY_IMAGES_EXT'] = 'png';
$GLOBALS['CONFIG_STATS_INVENTORY_CACHE'] = '60';
$GLOBALS['CONFIG_STATS_SKILLS_ENABLED'] = '1';
$GLOBALS['CONFIG_STATS_SKILLS_GUESTS'] = '1';
$GLOBALS['CONFIG_STATS_SKILLS_VIEWABLE'] = '2';
$GLOBALS['CONFIG_STATS_SKILLS_ACTIVE'] = '1';
$GLOBALS['CONFIG_STATS_SKILLS_PASSIVE'] = '1';
$GLOBALS['CONFIG_STATS_SKILLS_IMAGES'] = 'http://dragoneyecms.com/skills/';
$GLOBALS['CONFIG_STATS_SKILLS_IMAGES_EXT'] = 'png';
$GLOBALS['CONFIG_STATS_SKILLS_CACHE'] = '60';
$GLOBALS['CONFIG_STATS_ACCOUNT_SIGNATURE_ENABLED'] = '1';
$GLOBALS['CONFIG_STATS_ACCOUNT_SIGNATURE_GUESTS'] = '1';
$GLOBALS['CONFIG_STATS_ACCOUNT_SIGNATURE_CACHE'] = '120';
$GLOBALS['CONFIG_STATS_PLAYER_SIGNATURE_ENABLED'] = '1';
$GLOBALS['CONFIG_STATS_PLAYER_SIGNATURE_GUESTS'] = '1';
$GLOBALS['CONFIG_STATS_PLAYER_SIGNATURE_CACHE'] = '60';
$GLOBALS['CONFIG_STATS_RAID_ENABLED'] = '1';
$GLOBALS['CONFIG_STATS_RAID_GUESTS'] = '1';
$GLOBALS['CONFIG_STATS_RAID_TIME_DIED'] = '1';
$GLOBALS['CONFIG_STATS_RAID_LEVEL'] = '1';
$GLOBALS['CONFIG_STATS_RAID_ONLINE_STATUS'] = '1';
$GLOBALS['CONFIG_STATS_RAID_MIN_LEVEL'] = '70';
$GLOBALS['CONFIG_STATS_RAID_MAX_LEVEL'] = '80';
$GLOBALS['CONFIG_STATS_RAID_CACHE'] = '60';
$GLOBALS['CONFIG_STATS_CASTLE_ENABLED'] = '1';
$GLOBALS['CONFIG_STATS_CASTLE_GUESTS'] = '1';
$GLOBALS['CONFIG_STATS_CASTLE_CACHE'] = '60';
$GLOBALS['CONFIG_STATS_TOP_PVP_ENABLED'] = '1';
$GLOBALS['CONFIG_STATS_TOP_PVP_GUESTS'] = '1';
$GLOBALS['CONFIG_STATS_TOP_PVP_RESULTS'] = '100';
$GLOBALS['CONFIG_STATS_TOP_PVP_RESULTS_PER_PAGE'] = '5';
$GLOBALS['CONFIG_STATS_TOP_PVP_ORDER'] = '1';
$GLOBALS['CONFIG_STATS_TOP_PVP_CACHE'] = '60';
$GLOBALS['CONFIG_STATS_TOP_PK_ENABLED'] = '1';
$GLOBALS['CONFIG_STATS_TOP_PK_GUESTS'] = '1';
$GLOBALS['CONFIG_STATS_TOP_PK_RESULTS'] = '100';
$GLOBALS['CONFIG_STATS_TOP_PK_RESULTS_PER_PAGE'] = '5';
$GLOBALS['CONFIG_STATS_TOP_PK_ORDER'] = '1';
$GLOBALS['CONFIG_STATS_TOP_PK_CACHE'] = '60';
$GLOBALS['CONFIG_STATS_TOTAL_PVP_ENABLED'] = '0';
$GLOBALS['CONFIG_STATS_TOTAL_PVP_CACHE'] = '120';
$GLOBALS['CONFIG_STATS_TOTAL_PK_ENABLED'] = '0';
$GLOBALS['CONFIG_STATS_TOTAL_PK_CACHE'] = '120';
