<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_TEMPLATE_DEFAULT'] = 'default';
$GLOBALS['CONFIG_TEMPLATE_SELECTED'] = 'default';
$GLOBALS['CONFIG_TEMPLATE_NAME'] = 'Default Template';
$GLOBALS['CONFIG_TEMPLATE_DESCRIPTION'] = 'First free open-source Lineage 2 CMS System.';
$GLOBALS['CONFIG_TEMPLATE_KEYWORDS'] = 'lineage2, cms, lineage, dragon, eye, forum, statistics';
$GLOBALS['CONFIG_TEMPLATE_AUTHOR'] = 'DragonEyeCMS';
$GLOBALS['CONFIG_TEMPLATE_IMAGES'] = 'images';
$GLOBALS['CONFIG_TEMPLATE_DEFAULT_LANG'] = 'english';
