<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_VOTE_ENABLED'] = '0';
$GLOBALS['CONFIG_VOTE_WEBSITES'] = array(array('L2RANKING', 'http://l2ranking.com/images/vote.png', 'http://yourservervotelink', '73', '43200', '2'));
$GLOBALS['CONFIG_VOTE_CHECK_METHOD'] = '2';
