<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['DBQUERY_CHECK_ACCOUNT'] = 'SELECT * FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CHECK_CHAR'] = 'SELECT * FROM %s WHERE %s = \'%s\' and %s = \'%s\'';
$GLOBALS['DBQUERY_CHECK_CLAN'] = 'SELECT * FROM %s WHERE %s = \'%s\' and %s in (SELECT %s FROM %s WHERE %s = \'%s\')';
$GLOBALS['DBQUERY_CHECK_EMAIL'] = 'SELECT * FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CHECK_LOGIN'] = 'SELECT * FROM %s WHERE %s = \'%s\' and %s = %s';
$GLOBALS['DBQUERY_CHECK_STATS_ACCESS'] = 'SELECT * FROM %s WHERE %s = \'%s\' and %s in (\'%s\', \'%s\', \'%s\', \'7\')';
$GLOBALS['DBQUERY_ACCOUNT_DATA'] = 'SELECT %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_SIGNATURE_ACC'] = 'SELECT SUM(%s), SUM(%s), SUM(%s) FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CHAR_DATA'] = 'SELECT %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, (SELECT %s FROM %s WHERE %s=%s) FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CLAN_DATA'] = 'SELECT %s, %s, %s, %s, (SELECT %s FROM %s WHERE %s = %s), (SELECT COUNT(*) FROM %s WHERE %s = %s) FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_MEMBERS_DATA'] = 'SELECT %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CREATE_ACCOUNT_L2J'] = 'INSERT INTO %s (%s, %s, %s, %s, %s) VALUES (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';
$GLOBALS['DBQUERY_CREATE_ACCOUNT_L2OFF_SSN'] = 'INSERT INTO [%s](%s, %s, %s, %s, %s, %s, %s, %s, %s) VALUES (\'%s\', \'%s\', \'%s\', 0, \'telphone\', \'123456\', \'\', \'\', 1)';
$GLOBALS['DBQUERY_CREATE_ACCOUNT_L2OFF_UAC'] = 'INSERT INTO %s (%s, %s, %s) VALUES (\'%s\', 1, \'%s\')';
$GLOBALS['DBQUERY_CREATE_ACCOUNT_L2OFF_UAU'] = 'INSERT INTO %s (%s, %s, %s, %s, %s, %s) VALUES (\'%s\', CONVERT(binary, %s), \'%s\', \'%s\', CONVERT(binary, \'%s\'), CONVERT(binary, \'%s\'))';
$GLOBALS['DBQUERY_CREATE_ACCOUNT_L2OFF_UIF'] = 'INSERT INTO %s (%s, %s, %s) VALUES (\'%s\', \'%s\', \'99\')';
$GLOBALS['DBQUERY_MCHECK_CREATE'] = 'INSERT INTO mail_check (username, email, password, ip, check_id, time, refer) VALUES (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';
$GLOBALS['DBQUERY_MCHECK_CHECK'] = 'SELECT * FROM mail_check WHERE username = \'%s\' and check_id = \'%s\' and ip = \'%s\'';
$GLOBALS['DBQUERY_MCHECK_DATA'] = 'SELECT username, email, password, refer FROM mail_check WHERE username = \'%s\' and check_id = \'%s\' and ip = \'%s\'';
$GLOBALS['DBQUERY_MCHECK_DELETE'] = 'DELETE FROM mail_check WHERE username = \'%s\'';
$GLOBALS['DBQUERY_MCHECK_CHECK_EXPIRED'] = 'SELECT * FROM mail_check WHERE username = \'%s\' and time <= \'%s\'';
$GLOBALS['DBQUERY_1_1'] = 'SELECT %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_1_1N'] = 'SELECT %s FROM %s WHERE %s = %s';
$GLOBALS['DBQUERY_2_1'] = 'SELECT %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_3_1'] = 'SELECT %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_LAST_LOGGED'] = 'SELECT %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CHANGE_PASSWORD'] = 'UPDATE %s SET %s=%s WHERE %s=\'%s\'';
$GLOBALS['DBQUERY_CHANGE_VIEWSET'] = 'UPDATE %s SET %s=\'%s\' WHERE %s=\'%s\'';
$GLOBALS['DBQUERY_CHANGE_SIGNATURE'] = 'UPDATE %s SET %s=\'%s\' WHERE %s=\'%s\'';
$GLOBALS['DBQUERY_PLAYERS_ONLINE'] = 'SELECT COUNT(*) FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_L2OFF_PLAYERS_ONLINE'] = 'SELECT TOP 1 %s FROM %s WITH (nolock) ORDER BY %s DESC';
$GLOBALS['DBQUERY_CASTLES'] = 'SELECT %s, %s, (SELECT %s FROM %s WHERE %s = %s), (SELECT %s FROM %s WHERE %s = (SELECT %s FROM %s WHERE %s = %s)) FROM %s';
$GLOBALS['DBQUERY_RAIDS'] = 'SELECT %s, %s, %s FROM %s JOIN %s ON %s = %s and %s >= \'%s\' and %s <= \'%s\'';
$GLOBALS['DBQUERY_L2OFF_RAIDS'] = 'SELECT %s, %s FROM %s WHERE %s IN(%s) ORDER by %s';
$GLOBALS['DBQUERY_TOP_PVP'] = 'SELECT %s, %s, %s FROM %s WHERE %s >= \'%s\'';
$GLOBALS['DBQUERY_TOP_PK'] = 'SELECT %s, %s, %s FROM %s WHERE %s >= \'%s\'';
$GLOBALS['DBQUERY_ADD_POINTS'] = 'UPDATE %s SET %s = %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_ADD_REFER_POINTS'] = 'UPDATE %s SET %s = %s + 1 WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_REMOVE_POINTS'] = 'UPDATE %s SET %s = %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_L2OFF_GET_MAIL'] = '(SELECT %s FROM %s WHERE %s = \'%s\')';
$GLOBALS['DBQUERY_SKILLS_DATA'] = 'SELECT %s, %s FROM %s WHERE %s = \'%s\' and %s = \'%s\'';
$GLOBALS['DBQUERY_INVENTORY_DATA'] = 'SELECT %s, %s, %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_L2OFF_INVENTORY_DATA'] = 'SELECT %s, %s, %s, %s, %s FROM %s WHERE %s = \'%s\' and %s not in (%s)';
$GLOBALS['DBQUERY_L2OFF_PAPERDOLL'] = 'SELECT %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_L2OFF_PAPERDOLL_ID'] = '(SELECT %s FROM %s WHERE %s = %s and %s = %s)';
$GLOBALS['DBQUERY_STAT_SUM'] = 'SELECT SUM(%s) FROM %s';
