<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_DONATE_ENABLED'] = '0';
$GLOBALS['CONFIG_DONATE_CURRENCY'] = '2';
$GLOBALS['CONFIG_DONATE_MULTIPLIER'] = '1';
$GLOBALS['CONFIG_DONATE_PAYPAL_ENABLE'] = '0';
$GLOBALS['CONFIG_DONATE_PAYPAL_MULTIPLIER'] = '1';
$GLOBALS['CONFIG_DONATE_PAYPAL_TEST'] = '1';
$GLOBALS['CONFIG_DONATE_PAYPAL_MAIL'] = 'yourmail@yourwebsite.com';
$GLOBALS['CONFIG_DONATE_MONEYBOOKERS_ENABLE'] = '0';
$GLOBALS['CONFIG_DONATE_MONEYBOOKERS_MULTIPLIER'] = '1';
$GLOBALS['CONFIG_DONATE_MONEYBOOKERS_MAIL'] = 'yourmail@yahoo.com';
$GLOBALS['CONFIG_DONATE_MONEYBOOKERS_SECRET_WORD'] = '252352';
$GLOBALS['CONFIG_DONATE_LOGS_EXTRA'] = 'd7eb8b3cb0abfef';
