<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_SHOP_ENABLED'] = '0';
$GLOBALS['CONFIG_SHOP_TELNET_IP'] = '127.0.0.1';
$GLOBALS['CONFIG_SHOP_TELNET_PORT'] = '12345';
$GLOBALS['CONFIG_SHOP_TELNET_PASSWORD'] = '123';
$GLOBALS['CONFIG_SHOP_TELNET_TIMEOUT'] = '15';
$GLOBALS['CONFIG_SHOP_CACHED_IP'] = '127.0.0.1';
$GLOBALS['CONFIG_SHOP_CACHED_PORT'] = '2012';
$GLOBALS['CONFIG_SHOP_CACHED_ADMIN'] = 'DragonEye';
$GLOBALS['CONFIG_SHOP_CACHED_TIMEOUT'] = '15';
$GLOBALS['CONFIG_SHOP_REFER_ENABLED'] = '0';
$GLOBALS['CONFIG_SHOP_VOTE_ENABLED'] = '0';
$GLOBALS['CONFIG_SHOP_DONATE_ENABLED'] = '0';
$GLOBALS['CONFIG_SHOP_FORUM_ENABLED'] = '0';
$GLOBALS['CONFIG_SHOP_REFER'] = array();
$GLOBALS['CONFIG_SHOP_VOTE'] = array();
$GLOBALS['CONFIG_SHOP_DONATE'] = array();
$GLOBALS['CONFIG_SHOP_FORUM'] = array();
